### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by L0rdH4x0r** [DHTMLGoodies/chessParser#3]
<pre>[Event "ProofOfConcept"]
[Site "Exploit"]
[Date "2015.??.??"]
[Round "?"]
[White "N.N."]
[Black "N.N."]
[Result "1-0"]
[Annotator ""]
[SetUp "1"]
[FEN "8/7P/8/8/1k15/8/P7/K7 w - - 0 1"]
[PlyCount "1"]
[EventDate "2015.??.??"]
[EventType "game"]
[EventCountry "GER"]

1. a3+</pre>

**Comment by DHTMLGoodies** [comment]
This issue was caused by the "1k15" line. 

When creating this parser, I noticed that some chess programs supported fens like

rnbqkbnr/pppppppp/32/PPPPPPPP/RNBQKBNR w KQkq - 0 1

instead of

rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1

i.e. 32 instead of 8/8/8/8

So, in your code, it interpreted "15" as 15 empty squares(instead of 6(1+5)).

I did a second test today and found that most programs does not support two digit number of empty squares. I have changed my script accordingly.

Your PGN parsed correctly after the modification

**Comment by L0rdH4x0r** [comment]
oO you are right!
I have downloaded a pgn file with a lot of tactical positions, where this one broke it.
Maybe it was an error in that pgn file. I forgot the name but maybe it was the 3,5k positions from gorgonian's site. I reduced it to a pgn with just the one position that broke it, but you figured it out correctly, I didn't even notice that 15 instead of 6 :DD Nevertheless good job, thanks!!!
